name: GuildAIEconomy
version: 1.2.0
main: com.guild.aieconomy.GuildAIEconomy
api-version: '1.20'
author: Starrrr332 / Antigravity AI
description: Plugin de Economia Inteligente con Aldeanos Chatbot Separados (Vanilla vs RPG 25k), EliteMobs e IA Gemini
softdepend: [Vault, EliteMobs]
commands:
  guildai:
    description: Comando principal de la economía de gremio e IA
    aliases: [tienda, guildshop, aishop, customshop, vanillashop, rpgshop]
permissions:
  guildai.use:
    description: Permite abrir la tienda y hablar con el mercader
    default: true
  guildai.admin:
    description: Permite administrar el plugin, aldeanos, cofre e ítems custom
    default: op
